import { createApp } from "vue";
import "./style.css";
import "virtual:windi.css";
import App from "./App.vue";
import router from "@/router";
import { globalRegister } from "@/global";
const app = createApp(App);
app.use(globalRegister);
app.use(router);
app.mount("#app");
